<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Servicios\Establecimientos\ZSports.Establecimientos.Contracts\ZSports.Establecimientos.Contracts.csproj" />
    <ProjectReference Include="..\Servicios\Establecimientos\ZSports.Establecimientos.Domain\ZSports.Establecimientos.Domain.csproj" />
  </ItemGroup>

</Project>
